### ISSUE TITLE
Cant get it to scrape nice

### ISSUE THREAD

**Issue by WnndGws** [WnndGws/OneOffCodes#12]
When i run code in isolation it works.

https://github.com/WnndGws/OneOffCodes/commit/a77bb4f95d5ca02cef02fa64ce526cd031d5c51a

**Comment by ammgws** [comment]
What do you want it to do vs what actually happens?

**Comment by WnndGws** [comment]
Want it to take url and download all images on it

What it actually does is overwrite images with image0.

Will write better bug report if neededw hen have 10mins free

**Comment by ammgws** [comment]
Works now, check the last couple of commits.

(Meant to push to my branch instead of your repo. Oops.)
