### ISSUE TITLE
Code review for Boxing3.1

### ISSUE THREAD

**Issue by WnndGws** [WnndGws/OneOffCodes#15]
Think I have finished it, now looking for errors/inefficiencies etc.

**Comment by ammgws** [comment]
Why have you reverted to `urllib` again after fin using `requests` last time?

**Comment by WnndGws** [comment]
Just what I am used to. Is one better than the other?

**Comment by ammgws** [comment]
Requests is basically a wrapper around urllib, but it is seen as more "Pythonic" due to its easy-to-use API. It's probably one of the most downloaded Python packages.

> **Warning:** Recreational use of the Python standard library for HTTP may result in dangerous side-effects, including: security vulnerabilities, verbose code, reinventing the wheel, constantly reading documentation, depression, headaches, or even death.
